#!/usr/bin/env python
"""
sets core.fileMode=false for git repos
mostly for Windows, particularly Cygwin
"""
import os
from subprocess import run
#
from pythonutils.gitcommon import codepath

rdir = codepath()

print('setting fileMode=false for all directories under {}'.format(rdir))
dlist = [x for x in rdir.iterdir() if x.is_dir()]
for d in dlist:
    run(['git','config','core.filemode','false'],cwd=str(d))
