#!/usr/bin/env python
from subprocess import run,PIPE
#
from pythonutils.gitcommon import codepath

rdir = codepath()

dlist = [x for x in rdir.iterdir() if x.is_dir()]

branch=[]
for d in dlist:
    ret = run(['git','rev-parse','--abbrev-ref','HEAD'],stdout=PIPE,cwd=str(d))

    if ret.stdout != b"master\n":
        b = ret.stdout.decode('utf8').rstrip()
        branch.append((d,b))

if branch:
    print(branch)
