#!/usr/bin/env python
"""
for a root directory $rdir, assumes all subdirectories are Git repos
and pulls to the current branch
"""

from pythonutils.ChDir import ChDir
from time import sleep
from subprocess import run
from random import randrange
#
from pythonutils.gitcommon import codepath

rdir = codepath()

print('git push for all directories under {}'.format(rdir))
dlist = [x for x in rdir.iterdir() if x.is_dir()]
for d in dlist:
    with ChDir(d):
        print(' --> {}'.format(d))
        ret = run(['git','pull'])
        
        if ret.stderr is not None:
            print('{} had error git pull {}'.format(d,ret.stderr))

        sleep(randrange(10)*.1) # don't hammer the remote server, delay of 0-1 second

