#!/usr/bin/env python
"""
for a root directory $rdir, assumes all subdirectories are Git repos
and pulls to the current branch
"""

from time import sleep
from subprocess import run,PIPE,TimeoutExpired
from random import randrange
#
from pythonutils.gitcommon import codepath

rdir = codepath()

dlist = [x for x in rdir.iterdir() if x.is_dir()]

failed=[]
for d in dlist:
    print(' --> {}'.format(d))
    try:
        ret = run(['git','pull'],stderr=PIPE,timeout=10, cwd=str(d))
    except TimeoutExpired:
        failed.append(d)

    if ret.returncode != 0:
        print('{} had error git pull {}'.format(d,ret.stderr.decode('utf8')))

    sleep(randrange(10)*.1) # don't hammer the remote server, delay of 0-1 second

if failed:
    print('paths with git pull ERROR:')
    print('\n'.join(failed))
