#!/usr/bin/env python
"""
detects uncommitted work/files in all git repos under a directory
"""
import subprocess as S
#
from pythonutils.gitcommon import codepath

def gitpushall(rdir):
    dlist = [x for x in rdir.iterdir() if x.is_dir()]

    dir_topush = []
    for d in dlist:
        for c in (['git','--no-pager','diff','HEAD'], # check for uncommitted work
                  ['git','log','--branches','--not','--remotes'],     # check for uncommitted branches (?)
                  ['git','ls-files','-o','-d','--exclude-standard']): # check for uncommitted files
            try:
                ret = S.run(c, stdout=S.PIPE, stderr=S.DEVNULL, timeout=10, cwd=str(d))
                ret.check_returncode()
                if ret.stdout:
                    dir_topush.append(d)
            except S.CalledProcessError as e:
                print('Error in  {}'.format(d,e.output))
                break

    return dir_topush

if __name__ == '__main__':
    rdir = codepath()
    dir_topush = gitpushall(rdir)
    if dir_topush:
        print('\n'.join((str(d) for d in dir_topush)))
