#!/usr/bin/env python
from pythonutils import Path
from subprocess import run,DEVNULL,PIPE

from argparse import ArgumentParser
p = ArgumentParser()
p.add_argument('rdir',help='root directory to search for active drive-google connections',nargs='?',default='~')
p = p.parse_args()

rdir = Path(p.rdir).expanduser()

try:
    [run(['drive','deinit'],cwd=str(d)) for d in rdir.rglob('.gd') if (d.is_dir() and (d/'credentials.json').is_file())]
except PermissionError:
    pass

#try:
#    [print(d) for d in rdir.rglob('.gd') if (d.is_dir() and (d/'credentials.json').is_file())]
#except PermissionError:
#    pass
