#!/bin/bash
[[ $# -eq 0 ]] && echo "Usage: eps2pdf input.eps" && exit 1
if [[ $# -eq 2 ]]; then
OutFN=$2
else
OutFN=joined.pdf
fi
#if [[ $# -eq 3 ]]; then
#Orient=$3
#fi


gs -sDEVICE=pdfwrite \
   -dRotatePages=true \
   -dEPSFitPage \
   -dNOPAUSE -dBATCH -dSAFER \
   -sOutputFile=$OutFN \
   $1
#-dEPSFitPage
#-dAutoRotatePages=/PageByPage \ #didn't work for matlab eps
#   -c "<</Orientation 2>> setpagedevice" \ # didn't work
#    -c quit


echo wrote $1 to $OutFN
