#!/usr/bin/env python

MAXSIZE=10e6  #[bytes]

from pythonutils import Path
from colorama import init,Fore,Back
init()

from argparse import ArgumentParser
p = ArgumentParser(description='searches for TEXT under DIR and echos back filenames')
p.add_argument('txt',help='text to search for') #required
p.add_argument('pat',help='glob pattern',nargs='?',default='*')
p.add_argument('rdir',help='root dir to search',nargs='?',default='.')
p = p.parse_args()

txt=p.txt
mat=[]

flist = Path(p.rdir).expanduser().rglob(p.pat)
for f in flist:
    if f.is_file() and f.stat().st_size<MAXSIZE:
        with f.open('r') as o:
            here = False
            matchinglines=[]
            try:
                for i,l in enumerate(o):
                    if not txt in l:
                        continue
                    matchinglines.append('{}: {}'.format(i,l))
                    here=True
            except UnicodeDecodeError as e:
                print('error on file {}  {}'.format(f,e))

        if here:
            print(Back.MAGENTA + str(f))
            print(Back.BLACK + '\n'.join(matchinglines))
            mat.append(f)

print('\n'.join([str(m) for m in mat]))


