#!/usr/bin/env python
"""
recursively find video files based on extension
"""
from subprocess import run,PIPE

from argparse import ArgumentParser
p = ArgumentParser()
p.add_argument('path',help='root path to start recursive search',nargs='?',default='.')
p = p.parse_args()

ret = run(['find',p.path,'-regextype','posix-egrep','-type','f',
     '-iregex','.*\.(avi|mov|mp4|mpg|mpeg|webm|ogv|mkv|wmv)$'],stdout=PIPE,stderr=PIPE)

vids = ret.stdout.decode('utf8').split('\n')

print('\n'.join(vids))