#!/bin/bash
# Michael Hirsch
# for connecting to BU research grid shares
# requires being on BU network or via VPN

#be sure username was specified
[[ $# -eq 1 ]] || { echo "you must specify your BU username e.g.   mU jdoe"; exit 1; }


#take care of hung up connections
uU
user=$1 #your kerberos username
# user parameters
sshfsHost=engineering-grid.bu.edu
sshfsDir=/ad/eng/research/

#now connect
echo mounting AD U
sshfs \
      -o sshfs_debug \
      -o follow_symlinks \
      -o PubKeyAuthentication=no \
      $user@"$sshfsHost":"$sshfsDir" \
      ~/U
#-d
# dont use -C from office, it's half the speed due to CPU load of server!
