#!/bin/bash
# Michael Hirsch
# for connecting to your BU personal network drive
# requires being on BU network or via VPN

#be sure username was specified
[[ $# -eq 1 ]] || { echo "you must specify your BU username e.g.   mU jdoe"; ex$

user=$1 #your BU kerberos login
#take care of hung up connections
uX

sshfsHost=engineering-grid.bu.edu
sshfsDir=/ad/eng/users/${user:0:1}/${user:1:1}/$user/

#now connect
echo Mounting AD X
sshfs -o sshfs_debug \
      -o follow_symlinks \
      -o PubKeyAuthentication=no \
      $user@"$sshfsHost":"$sshfsDir" \
      ~/X

# dont use -C from office, it's half the speed due to CPU load of server!
